name: Check the source code
on:
  pull_request:
    branches:
      - main
jobs:
  check_code:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '20.11.1'
      - name: Install dependencies
        run: npm install
      - name: Prettier
        run: npm run format
      - name: ESLint
        run: npm run lint
