name: Set assignees

on:
  pull_request_target:
    types:
      - opened

jobs:
  set-assignees:
    name: Set assignees
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set assignees
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            const response = await github.rest.issues.get({
              owner,
              repo,
              issue_number: prNumber,
            })
            const { assignees } = response.data;

            if (assignees.length === 0) {
              let assignee = context.actor;
              const branchName = context.payload.pull_request.head.ref;

              if (branchName.startsWith('dependabot/')) {
                assignee = owner;
              }

              await github.rest.issues.addAssignees({
                owner: owner,
                repo: repo,
                issue_number: prNumber,
                assignees: [assignee]
              });
            }
